name: bactopia-summary
version: 1.4.11
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - coloredlogs=14.0
  - coreutils=8.31
  - executor=23.1
  - fasteners=0.14.1
  - humanfriendly=8.2
  - jinja2=2.11.2
  - libcxx=11.0.0
  - libffi=3.2.1
  - markupsafe=1.1.1
  - monotonic=1.5
  - ncurses=6.2
  - openssl=1.1.1h
  - pip=20.2.4
  - property-manager=3.0
  - python=3.9.0
  - python_abi=3.9
  - readline=8.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tzdata=2020d
  - verboselogs=1.7
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
