name: bactopia-phyloflash
version: 1.4.x
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.1.5
  - bbmap=38.76
  - bedtools=2.29.2
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - biopython=1.76
  - bowtie=1.2.3
  - bwidget=1.9.14
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - certifi=2019.11.28
  - curl=7.68.0
  - emirge=0.61.1
  - fontconfig=2.13.1
  - freetype=2.10.0
  - fribidi=1.0.5
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - giflib=5.2.1
  - glib=2.58.3
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.4.0
  - htslib=1.10.2
  - icu=64.2
  - iqtree=1.6.12
  - jpeg=9c
  - krb5=1.16.4
  - lcms2=2.9
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.68.0
  - libdeflate=1.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - llvm-openmp=8.0.1
  - lz4-c=1.8.3
  - mafft=7.455
  - make=4.2.1
  - ncurses=6.1
  - numpy=1.16.5
  - openjdk=11.0.1
  - openmp=8.0.1
  - openssl=1.1.1d
  - pango=1.42.4
  - pcre=8.44
  - perl=5.26.2
  - phyloflash=3.3b3
  - pigz=2.3.4
  - pip=20.0.2
  - pixman=0.38.0
  - pthread-stubs=0.4
  - pysam=0.15.3
  - python=2.7.15
  - r-assertthat=0.2.1
  - r-backports=1.1.5
  - r-base=3.6.2
  - r-cli=2.0.1
  - r-colorspace=1.4
  - r-crayon=1.3.4
  - r-digest=0.6.24
  - r-ellipsis=0.3.0
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-getopt=1.20.3
  - r-ggdendro=0.1
  - r-ggplot2=3.2.1
  - r-glue=1.3.1
  - r-gtable=0.3.0
  - r-labeling=0.3
  - r-lattice=0.20
  - r-lazyeval=0.2.2
  - r-lifecycle=0.1.0
  - r-magrittr=1.5
  - r-mass=7.3
  - r-matrix=1.2
  - r-mgcv=1.8
  - r-munsell=0.5.0
  - r-nlme=3.1
  - r-optparse=1.6.4
  - r-pillar=1.4.3
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.5
  - r-r6=2.4.1
  - r-rcolorbrewer=1.1
  - r-rcpp=1.0.3
  - r-reshape2=1.4.3
  - r-rlang=0.4.4
  - r-scales=1.1.0
  - r-stringi=1.4.6
  - r-stringr=1.4.0
  - r-tibble=2.1.3
  - r-utf8=1.1.4
  - r-vctrs=0.2.2
  - r-viridislite=0.3.0
  - r-withr=2.1.2
  - r-zeallot=0.1.0
  - readline=8.0
  - samtools=1.10
  - scipy=1.2.1
  - sed=4.7
  - setuptools=44.0.0
  - spades=3.14.0
  - sqlite=3.30.1
  - tbb=2019.9
  - tk=8.6.10
  - tktable=2.10
  - vsearch=2.14.2
  - wheel=0.34.2
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.4.4
