image: bactopia/bactopia-ci:latest

before_script:
  - BACTOPIA=/opt/conda/envs/bactopia
  - chmod 755 bactopia
  - cp bactopia ${BACTOPIA}/bin
  - chmod 755 bin/helpers/*
  - cp bin/helpers/* ${BACTOPIA}/bin
  - VERSION=`bactopia version | cut -d " " -f 2`
  - mkdir ${BACTOPIA}/share/bactopia-${VERSION}/
  - cp -r bin/ conda/ conf/ templates/ tools/ main.nf nextflow.config ${BACTOPIA}/share/bactopia-${VERSION}/

stages:
    - test-bactopia-commands
    - test-bactopia-nextflow

bactopia-commands:
    stage: test-bactopia-commands
    only:
        - master
    script:
        - which bactopia
        - bactopia version
        - bactopia --version
        - bactopia search
        - bactopia prepare
        - bactopia tools

bactopia-nextflow:
    stage: test-bactopia-nextflow
    only:
        - master
    script:
        - bactopia --help
        - ls tools | xargs -I {} sh -c 'cd /tmp/ && bactopia tools {} --help'
