image: continuumio/miniconda3

before_script:
  - conda create -y -n bactopia -c conda-forge -c bioconda bactopia
  - source activate bactopia
  - rm -v /opt/conda/envs/bactopia/bin/bactopia
  - chmod 755 bactopia
  - cp bactopia /opt/conda/envs/bactopia/bin
  - ls bin/helpers/ | xargs -I {} rm -rv /opt/conda/envs/bactopia/bin/{}
  - chmod 755 bin/helpers/*
  - cp bin/helpers/* /opt/conda/envs/bactopia/bin
  - rm -rfv /opt/conda/envs/bactopia/share/bactopia-`bactopia version | cut -d " " -f 2`/*
  - cp -r bin/ conda/ conf/ templates/ tools/ main.nf nextflow.config /opt/conda/envs/bactopia/share/bactopia-1.3.0

stages:
    - test-bactopia-commands
    - test-bactopia-nextflow

bactopia-commands:
    stage: test-bactopia-commands
    only:
        - master
    script:
        - which bactopia
        - bactopia version
        - bactopia --version
        - bactopia search
        - bactopia prepare
        - bactopia tools

bactopia-nextflow:
    stage: test-bactopia-nextflow
    only:
        - master
    script:
        - bactopia --help
        - bactopia tools fastani --help
