image: bactopia/bactopia-ci:latest

before_script:
  - BACTOPIA=/opt/conda/envs/bactopia
  - FQ_DIR=tests/real-fastqs/
  - CONDA_DIR=conda-envs/
  - COVERAGE="--coverage 20"
  - chmod 755 bactopia
  - cp bactopia ${BACTOPIA}/bin
  - chmod 755 bin/helpers/*
  - cp bin/helpers/* ${BACTOPIA}/bin
  - VERSION=`bactopia version | cut -d " " -f 2`
  - BACTOPIA_VERSION="${VERSION%.*}.x"
  - mkdir ${BACTOPIA}/share/bactopia-${BACTOPIA_VERSION}/
  - cp -r bin/ conda/ conf/ docs/ templates/ tools/ main.nf nextflow.config ${BACTOPIA}/share/bactopia-${BACTOPIA_VERSION}/

stages:
    - subcommand_stage
    - build_stage
    - test_stage

bactopia-version:
    stage: subcommand_stage
    only:
        - master
    script:
        - which bactopia
        - bactopia version
        - bactopia --version
        - bactopia versions

bactopia-citation:
    stage: subcommand_stage
    only:
        - master
    script:
        - bactopia citation
        - bactopia --citation
        - bactopia citations

bactopia-search:
    stage: subcommand_stage
    only:
        - master
    script:
        - bactopia search
        - bactopia search --help
        - bactopia search PRJNA480016 --limit 5
        - bactopia search 1280 --exact_taxon --limit 5
        - bactopia search "staphylococcus aureus" --limit 5
        - bactopia search SAMN01737350 --limit 5
        - bactopia search SRR578340 --limit 5
        - bactopia search SAMN01737350,SRR578340 --limit 5 --outdir test-search --prefix test
        - bactopia search tests/test-search-accessions.txt --limit 5

bactopia-datasets:
    stage: subcommand_stage
    only:
        - master
    script:
        - bactopia datasets
        - bactopia datasets --help

bactopia-prepare:
    stage: subcommand_stage
    only:
        - master
    script:
        - bactopia prepare
        - bactopia prepare --help
        - bactopia prepare ${FQ_DIR}

bactopia-build:
    stage: build_stage
    tags:
        - local-docker
    only:
        - master
    script:
        - bactopia build
        - bactopia build --help
        - bactopia build conda/ ${CONDA_DIR}
    artifacts:
        paths:
            - conda-envs/

run-bactopia-se:
    stage: test_stage
    tags:
        - local-docker
    only:
        - master
    script:
        - bactopia --SE ${FQ_DIR}/SRR2838702SE.fastq.gz --sample SRR2838702SE --outdir runs/bactopia-se ${COVERAGE} --condadir ${CONDA_DIR} -ansi-log false
        - rm -rf .nextflow* work/

run-bactopia-pe:
    stage: test_stage
    tags:
        - local-docker
    only:
        - master
    script:
        - bactopia --R1 ${FQ_DIR}/SRR2838702_R1.fastq.gz --R2 ${FQ_DIR}s/SRR2838702_R2.fastq.gz --sample SRR2838702 --outdir runs/bactopia-pe ${COVERAGE} --condadir ${CONDA_DIR} -ansi-log false
        - rm -rf .nextflow* work/

run-bactopia-fofn:
    stage: test_stage
    tags:
        - local-docker
    only:
        - master
    script:
        - bactopia prepare ${FQ_DIR} > fastqs.txt
        - bactopia --fastqs fastqs.txt --outdir runs/bactopia-fofn ${COVERAGE} --condadir ${CONDA_DIR} -ansi-log false
        - rm -rf .nextflow* work/

run-bactopia-sra:
    stage: test_stage
    tags:
        - local-docker
    only:
        - master
    script:
        - bactopia --accession SRX1390609 --outdir runs/bactopia-sra ${COVERAGE} --condadir ${CONDA_DIR} -ansi-log false
        - rm -rf .nextflow* work/

run-bactopia-assembly:
    stage: test_stage
    tags:
        - local-docker
    only:
        - master
    script:
        - bactopia --accession GCF_002849995 --outdir runs/bactopia-assembly ${COVERAGE} --condadir ${CONDA_DIR} -ansi-log false
        - rm -rf .nextflow* work/

run-bactopia-accessions:
    stage: test_stage
    tags:
        - local-docker
    only:
        - master
    script:
        - bactopia --accessions tests/test-search-accessions.txt --outdir runs/bactopia-accessions ${COVERAGE} --condadir ${CONDA_DIR} -ansi-log false
        - rm -rf .nextflow* work/

run-bactopia-with-datasets:
    stage: test_stage
    tags:
        - local-docker
    only:
        - master
    script:
        - bactopia datasets --species "Staphylococcus aureus" --limit 10
        - git clone -b staphopia-v1 https://github.com/bactopia/bactopia-datasets.git
        - cp -r bactopia-datasets/species-specific/ datasets/
        - rm -rf bactopia-datasets/
        - bactopia --accession GCF_003431365 --datasets datasets/ --species "Staphylococcus aureus" --outdir runs/bactopia-with-datasets ${COVERAGE} --condadir ${CONDA_DIR} -ansi-log false
        - rm -rf .nextflow* work/
