name: bactopia
version: 1.5.3
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - ariba=2.14.5
  - bactopia=1.5.3
  - bcftools=1.11
  - beautifulsoup4=4.9.3
  - biopython=1.78
  - blast=2.5.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bowtie2=2.3.5.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - capnproto=0.6.1
  - cd-hit=4.8.1
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - coloredlogs=15.0
  - conda=4.8.4
  - conda-package-handling=1.7.2
  - coreutils=8.31
  - cryptography=3.3.1
  - curl=7.71.1
  - cycler=0.10.0
  - dendropy=4.5.1
  - enum34=1.1.10
  - executor=23.2
  - fasteners=0.14.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - gsl=2.6
  - htslib=1.11
  - humanfriendly=9.1
  - icu=67.1
  - idna=2.10
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libidn2=2.3.0
  - liblapack=3.9.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=8.0.1
  - lxml=4.6.2
  - lz4-c=1.9.2
  - mash=2.2.2
  - matplotlib-base=3.3.3
  - monotonic=1.5
  - mummer=3.23
  - ncbi-genome-download=0.3.0
  - ncurses=6.2
  - nextflow=20.10.0
  - numpy=1.19.4
  - olefile=0.46
  - openjdk=10.0.2
  - openmp=8.0.1
  - openssl=1.1.1h
  - perl=5.32.0
  - perl-threaded=5.26.0
  - pillow=8.0.1
  - pip=20.3.1
  - property-manager=3.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pyfastaq=3.17.0
  - pymummer=0.10.3
  - pyopenssl=20.0.0
  - pyparsing=2.4.7
  - pysam=0.16.0.1
  - pysocks=1.7.1
  - python=3.6.12
  - python-dateutil=2.8.1
  - python_abi=3.6
  - readline=8.0
  - requests=2.25.0
  - ruamel_yaml=0.15.80
  - samtools=1.11
  - sed=4.8
  - setuptools=49.6.0
  - six=1.15.0
  - soupsieve=2.0.1
  - spades=3.14.1
  - sqlite=3.34.0
  - tbb=2020.2
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.54.1
  - unzip=6.0
  - urllib3=1.25.11
  - verboselogs=1.7
  - wget=1.20.1
  - wheel=0.36.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5

