name: kleborate
description: Screening Klebsiella genome assemblies for MLST, sub-species, and other Klebsiella related genes of interest
keywords:
  - enterics
  - fasta
  - klebsiella
  - resistance
  - virulence
modules:
  - kleborate
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Staphylococcus aureus fasta file.
      pattern: "*.{fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - kleborate_tsv:
      type: file
      description: A summary of the per-sample kleborate result
      pattern: "*-summary.tab"
  - kleborate_all_tsv:
      type: file
      description: A merged TSV of all Kleborate result files
      pattern: "agrvate.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
