{% set name = "bactopia" %}
{% set version = "1.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0

source:
  #url: https://github.com/bactopia/bactopia/archive/v{{version}}.tar.gz
  url: http://staphopia.emory.edu/static/v1.0.1.tar.gz
  sha256: 77ccd496dfe016096f270bd696aa7f9a340743ed5a8b96c82e4b4fbb641c5fd3

requirements:
  run:
    - ariba
    - beautifulsoup4
    - biopython
    - blast
    - cd-hit
    - conda
    - executor
    - lxml
    - mash
    - ncbi-genome-download
    - nextflow
    - python >3.6
    - unzip
    - urllib3
    - wget

test:
  commands:
    - "bactopia --help"
    - "bactopia --version"
    - "setup-datasets --version"
    - "setup-datasets . --depends"

about:
  home: https://github.com/bactopia/bactopia
  license: MIT
  license_file: LICENSE
  summary: A generic pipeline for the analysis of short-read bacterial sequences.
