name: mashtree
description: Quickly create a tree using Mash distances
keywords:
  - tree
  - mash
  - fasta
modules:
  - mashtree
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTAfiles
      pattern: "*.{fna,fna.gz,fasta,fasta.gz,fa,fa.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tree:
      type: file
      description: A Newick formatted tree file
      pattern: "*.{dnd}"
  - matrix:
      type: file
      description: A TSV matrix of pair-wise Mash distances
      pattern: "*.{tsv}"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
