name: ngmaster
description: Multi-antigen sequence typing for Neisseria gonorrhoeae
keywords:
  - fasta
  - Neisseria gonorrhoeae
  - serotype
modules:
  - ngmaster
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Neisseria gonorrhoeae fasta file.
      pattern: "*.{fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-sample ngmaster result
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all ngmaster result files
      pattern: "ngmaster.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
