name: fastani
description: fast alignment-free computation of whole-genome Average Nucleotide Identity (ANI)
keywords:
  - fastani
modules:
  - average nucleotide identity
  - fastani
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
 - query:
      type: file
      description: FASTA files to query against a reference
      pattern: "*.{fna,fna.gz}"
 - reference:
      type: file
      description: Reference FASTA to be queried against
      pattern: "*.{fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-reference fastANI result
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all fastANI result files
      pattern: "fastani.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
