name: emmtyper
description: emm-typing of Streptococcus pyogenes assemblies
keywords:
  - fasta
  - Streptococcus pyogenes
  - typing
modules:
  - emmtyper
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Streptococcus pyogenes fasta file.
      pattern: "*.{fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-sample emmtyper result
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all emmtyper result files
      pattern: "emmtyper.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
