blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/bactopia/bactopia/discussions/new?category=Ideas
    about: Share your ideas for new features
  - name: Ask a Question
    url: https://github.com/bactopia/bactopia/discussions/new?category=Questions
    about: Ask the community for help
  - name: Everything Else
    url: https://github.com/bactopia/bactopia/discussions/new?category=General
    about: The catchall for everything else!
