name: meningotype
description: Serotyping of Neisseria meningitidis
keywords:
  - fasta
  - Neisseria meningitidis
  - serotype
modules:
  - meningotype
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Neisseria meningitidis fasta file.
      pattern: "*.{fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-sample meningotype result
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all meningotype result files
      pattern: "meningotype.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
