name: bactopia-gtdb
version: 1.4.x
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - boost=1.70.0
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - capnproto=0.6.1
  - certifi=2020.6.20
  - dendropy=4.4.0
  - fastani=1.31
  - fasttree=2.1.10
  - gsl=2.6
  - gtdbtk=1.3.0
  - hmmer=3.1b2
  - icu=67.1
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libstdcxx-ng=9.3.0
  - lz4-c=1.9.2
  - mash=2.2.2
  - ncurses=6.2
  - numpy=1.19.1
  - openssl=1.1.1g
  - pip=20.2.2
  - pplacer=1.1.alpha19
  - prodigal=2.6.3
  - python=3.8.5
  - python_abi=3.8
  - readline=8.0
  - setuptools=49.6.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tqdm=4.48.2
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
