name: bactopia-ectyper
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=21.2.0
  - bcftools=1.13
  - biopython=1.79
  - blast=2.12.0
  - bowtie2=2.4.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - capnproto=0.6.1
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - cryptography=3.4.7
  - curl=7.77.0
  - ectyper=1.0.0
  - entrez-direct=13.9
  - expat=2.4.1
  - gsl=2.6
  - htslib=1.13
  - idna=2.10
  - iniconfig=1.1.1
  - krb5=1.19.1
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.77.0
  - libdeflate=1.7
  - libedit=3.1.20210216
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.15
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - lz4-c=1.9.3
  - mash=2.3
  - more-itertools=8.8.0
  - ncurses=6.2
  - numpy=1.21.0
  - openssl=1.1.1k
  - packaging=21.0
  - pandas=1.3.0
  - pcre=8.45
  - perl=5.26.2
  - perl-app-cpanminus=1.7044
  - perl-archive-tar=2.32
  - perl-base=2.23
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-digest-hmac=1.03
  - perl-digest-md5=2.55
  - perl-encode=2.88
  - perl-encode-locale=1.05
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-file-listing=6.04
  - perl-file-path=2.16
  - perl-file-temp=0.2304
  - perl-html-parser=3.72
  - perl-html-tagset=3.20
  - perl-html-tree=5.07
  - perl-http-cookies=6.04
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.18
  - perl-http-negotiate=6.01
  - perl-io-compress=2.087
  - perl-io-html=1.001
  - perl-io-socket-ssl=2.066
  - perl-io-zlib=1.10
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-libwww-perl=6.39
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-lwp-mediatypes=6.04
  - perl-lwp-protocol-https=6.07
  - perl-mime-base64=3.15
  - perl-mozilla-ca=20180117
  - perl-net-http=6.19
  - perl-net-ssleay=1.88
  - perl-ntlm=1.09
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.52
  - perl-socket=2.027
  - perl-storable=3.15
  - perl-test-requiresinternet=0.05
  - perl-time-local=1.28
  - perl-try-tiny=0.30
  - perl-types-serialiser=1.0
  - perl-uri=1.76
  - perl-www-robotrules=6.02
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44_01
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-simple=2.25
  - perl-xsloader=0.24
  - pip=21.1.3
  - pluggy=0.13.1
  - py=1.10.0
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.2.4
  - python=3.9.6
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.1
  - readline=8.1
  - requests=2.25.1
  - samtools=1.13
  - seqtk=1.3
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tbb=2020.3
  - tk=8.6.10
  - toml=0.10.2
  - tzdata=2021a
  - urllib3=1.26.6
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
