name: lissero
description: Serogroup typing prediction for Listeria monocytogenes
keywords:
  - fasta
  - Listeria monocytogenes
  - serogroup
modules:
  - lissero
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Listeria monocytogenes fasta file.
      pattern: "*.{fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-sample lissero result
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all lissero result files
      pattern: "lissero.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
