name: bactopia-eggnog
version: 1.4.x
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - biopython=1.76
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2019.11.28
  - diamond=0.9.35
  - eggnog-mapper=2.0.1
  - gettext=0.19.8.1
  - icu=67.1
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - libidn2=2.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.9
  - libstdcxx-ng=9.2.0
  - libunistring=0.9.10
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - ncurses=6.1
  - numpy=1.16.5
  - openssl=1.1.1g
  - pip=20.1.1
  - python=2.7.15
  - python_abi=2.7
  - readline=8.0
  - setuptools=44.0.0
  - sqlite=3.30.1
  - tk=8.6.10
  - wget=1.20.1
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
