name: bactopia-eggnog
version: 1.4.11
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.76
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2019.11.28
  - diamond=2.0.4
  - eggnog-mapper=2.0.1
  - gettext=0.19.8.1
  - icu=67.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.0.0
  - libffi=3.2.1
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libiconv=1.16
  - libidn2=2.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libunistring=0.9.10
  - llvm-openmp=11.0.0
  - lz4-c=1.9.2
  - ncurses=6.2
  - numpy=1.16.5
  - openssl=1.1.1h
  - pip=20.1.1
  - python=2.7.15
  - python_abi=2.7
  - readline=8.0
  - setuptools=44.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wget=1.20.1
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
