name: bactopia-fastani
version: 1.4.x
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.3
  - boost=1.70.0
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - enum34=1.1.6
  - fastani=1.3
  - icu=64.2
  - idna=2.8
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libstdcxx-ng=9.2.0
  - ncbi-genome-download=0.2.12
  - ncurses=6.1
  - numpy=1.18.1
  - openssl=1.1.1d
  - perl=5.26.2
  - pip=20.0.2
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.1
  - readline=8.0
  - rename=1.601
  - requests=2.22.0
  - setuptools=45.2.0
  - six=1.14.0
  - sqlite=3.30.1
  - tk=8.6.10
  - urllib3=1.25.7
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
