name: bactopia-commands

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]
    
jobs:
  bactopia-commands:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2
      - name: Setupo miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bactopia
          auto-activate-base: false
      - name: Install Dependencies
        run: bash setup-action-env.sh 
      - name: Staging
        run: |
          BACTOPIA=${CONDA}/envs/bactopia
          chmod 755 bactopia bin/helpers/*
          cp bactopia bin/helpers/* ${BACTOPIA}/bin
          VERSION=`${CONDA}/envs/bactopia/bin/bactopia version | cut -d " " -f 2`
          BACTOPIA_VERSION="${VERSION%.*}.x"
          mkdir ${BACTOPIA}/share/bactopia-${BACTOPIA_VERSION}/
          cp -r bin/ conda/ conf/ docs/ templates/ tools/ main.nf nextflow.config ${BACTOPIA}/share/bactopia-${BACTOPIA_VERSION}/
      - name: Test bactopia version
        run: |
          echo "Testing bactopia version"
          bactopia version
          bactopia --version
          bactopia versions
      - name: Test bactopia citation
        run: |
          echo "Testing bactopia citation"
          bactopia citation
          bactopia --citation
          bactopia citations
      - name: Test bactopia search
        run: |
          echo "Testing bactopia search"
          bactopia search
          bactopia search --version
          bactopia search --help         
      - name: Test bactopia datasets
        run: |
          echo "Testing bactopia datasets"
          bactopia datasets --version
          bactopia datasets --help
      - name: Test bactopia prepare
        run: |
          echo "Testing bactopia prepare"
          bactopia prepare
          bactopia prepare --version
          bactopia prepare --help
      - name: Test bactopia build
        run: |
          echo "Testing bactopia build"
          bactopia build --version
          bactopia build --help

          
