name: bactopia-search

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]
    
jobs:
  bactopia-search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: conda env create -f ${GITHUB_WORKSPACE}/environment.yml --prefix ${CONDA}/envs/bactopia
      - name: Staging
        run: |
          BACTOPIA=${CONDA}/envs/bactopia
          chmod 755 bactopia bin/helpers/*
          cp bactopia bin/helpers/* ${BACTOPIA}/bin
          VERSION=`bactopia version | cut -d " " -f 2`
          BACTOPIA_VERSION="${VERSION%.*}.x"
          mkdir ${BACTOPIA}/share/bactopia-${BACTOPIA_VERSION}/
          cp -r bin/ conda/ conf/ docs/ templates/ tools/ main.nf nextflow.config ${BACTOPIA}/share/bactopia-${BACTOPIA_VERSION}/
          echo "${CONDA}/envs/bactopia/bin" >> $GITHUB_PATH

      - name: Test BioProject (PRJNA480016)
        run: bactopia search PRJNA480016 --limit 5 --prefix PRJNA480016 && head PRJNA480016-accessions.txt

      - name: Test Tax ID (1280)
        run: bactopia search 1280 --exact_taxon --limit 5 --prefix 1280 && head 1280-accessions.txt

      - name: Test Species (S. aureus)
        run: bactopia search "staphylococcus aureus" --limit 5 --prefix saureus && head saureus-accessions.txt

      - name: Test BioSample (SAMN01737350)
        run: bactopia search SAMN01737350 --limit 5 --prefix SAMN01737350 && head SAMN01737350-accessions.txt

      - name: Test Run (SAMN01737350)
        run: bactopia search SRR578340 --limit 5 --prefix SRR578340 && head SRR578340-accessions.txt

      - name: Test Multiple Accessions 
        run: bactopia search SAMN01737350,SRR578340 --limit 5 --outdir test-search --prefix test && head test-search/test-accessions.txt

      - name: Test Accessions File
        run: bactopia search ${GITHUB_WORKSPACE}/tests/test-search-accessions.txt --limit 5 --prefix accfile && head accfile-accessions.txt
