name: docker-build-ghcr-release
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Login to GitHubContainer Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GHCR_TOKEN }}
          
      - name: Build and publish image to GitHub Container Registry
        run: bash bin/update-docker.sh ./ "ghcr.io/bactopia" 1
