name: pytest-bactopia

on: workflow_dispatch
  #schedule:
    # At 01:30 on Monday and Thursday
    #- cron:  '30 1 * * 1,4'

jobs:
  pytest-bactopia:
    runs-on: olaf
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2
        with:
          path: ${{ github.run_id }}/bactopia

      - name: Run Bactopia Tests
        run: |
          cd ${{ github.run_id }}/bactopia
          BACTOPIA_CI=/data/storage/bactopia-ci
          BACTOPIA_WORKSPACE="${GITHUB_WORKSPACE}/${{ github.run_id }}"
          source ${BACTOPIA_CI}/miniconda3/etc/profile.d/conda.sh
          mkdir ${BACTOPIA_WORKSPACE}/envs ${BACTOPIA_WORKSPACE}/pytest
          bash ${BACTOPIA_WORKSPACE}/bactopia/bin/gh-actions/setup-bactopia-env.sh ${BACTOPIA_WORKSPACE} ${BACTOPIA_WORKSPACE}/bactopia 0 "${BACTOPIA_WORKSPACE}/envs/bactopia-${GITHUB_RUN_ID}" "bactopia-${GITHUB_RUN_ID}"
          conda activate ${BACTOPIA_WORKSPACE}/envs/bactopia-${GITHUB_RUN_ID}
          export PATH=${GITHUB_WORKSPACE}/envs/bactopia-${GITHUB_RUN_ID}/bin:${PATH}
          uname -a && env
          cd ${BACTOPIA_WORKSPACE}/bactopia
          BACTOPIA_ARGS="--condadir ${BACTOPIA_CI}/envs/conda --test_data_dir ${BACTOPIA_CI}/bactopia-tests/data" TMPDIR=${BACTOPIA_WORKSPACE}/pytest pytest -n 12 --symlink --kwdof --ignore conda/ --ignore modules/local/bactopia-tools/ --tag bactopia

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs-debian
          path: |
            ${GITHUB_WORKSPACE}/pytest/pytest_workflow_*/*/log.out
            ${GITHUB_WORKSPACE}/pytest/pytest_workflow_*/*/log.err
            
      #- name: Cleanup
      #  if: always()
      #  run: rm -rf ${{ github.run_id }}
