name: test-bactopia-conda

on: workflow_dispatch
  #schedule:
    # At 01:30 on Monday and Thursday
    #- cron:  '30 1 * * 1,4'

jobs:
  bactopia-testing-conda:
    runs-on: olaf
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2

      - name: Checkout bactopia/bactopia-tests
        uses: actions/checkout@v2
        with:
          repository: bactopia/bactopia-tests
          path: bactopia-tests

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bactopia
          auto-activate-base: false

      - name: Setup Bactopia Environment
        run: |
          conda install -c conda-forge -c bioconda -y mamba
          bash ${GITHUB_WORKSPACE}/bin/gh-actions/setup-bactopia-env.sh ${CONDA} ${GITHUB_WORKSPACE} 1

      - name: Run Pytests
        env:
          SINGULARITY_CACHE: /data/storage/bactopia-ci/
          CONDA_CACHE: /data/storage/bactopia-ci/envs/conda
        run: |
          uname -a && env
          mkdir ${GITHUB_WORKSPACE}/pytest
          BACTOPIA_ARGS="--condadir ${CONDA_CACHE} --test_data_dir ${GITHUB_WORKSPACE}/bactopia-tests/data" TMPDIR=${GITHUB_WORKSPACE}/pytest pytest --symlink --kwdof --ignore conda/ --ignore modules/local/bactopia-tools/ --tag bactopia

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs-debian
          path: |
            ${GITHUB_ACTION_PATH}/pytest/pytest_workflow_*/*/log.out
            ${GITHUB_ACTION_PATH}/pytest/pytest_workflow_*/*/log.err
