name: test-bactopia-conda

on: workflow_dispatch
  #schedule:
    # At 01:30 on Monday and Thursday
    #- cron:  '30 1 * * 1,4'

jobs:
  bactopia-testing-conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2

      - name: Checkout bactopia/bactopia-tests
        uses: actions/checkout@v2
        with:
          repository: bactopia/bactopia-tests
          path: bactopia-tests

      - name: Free up Disk Space
        run: bash ${GITHUB_WORKSPACE}/bin/gh-actions/free-disk-space.sh

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bactopia
          auto-activate-base: false

      - name: Setup Bactopia Environment
        run: |
          conda install -c conda-forge -c bioconda -y mamba
          bash ${GITHUB_WORKSPACE}/bin/gh-actions/setup-bactopia-env.sh ${CONDA} ${GITHUB_WORKSPACE} 1
          bactopia build

      - name: Environment Information
        run: uname -a && env

      - name: Run Pytests
        run: BACTOPIA_ARGS="--test_data_dir ${GITHUB_WORKSPACE}/bactopia-tests/data" pytest --symlink --keep-workflow-wd --ignore conda/ --ignore modules/local/bactopia-tools/ --tag bactopia
