name: test-bactopia-conda

on: workflow_dispatch
  #schedule:
    # At 01:30 on Monday and Thursday
    #- cron:  '30 1 * * 1,4'

jobs:
  bactopia-testing-conda:
    runs-on: olaf
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2

      - name: Checkout bactopia/bactopia-tests
        uses: actions/checkout@v2
        with:
          repository: bactopia/bactopia-tests
          path: bactopia-tests

      - name: Run Bactopia Tests
        run: |
          BACTOPIA_CI=/data/storage/bactopia-ci
          BACTOPIA=$(pwd)
          source ${BACTOPIA_CI}/miniconda3/etc/profile.d/conda.sh
          conda activate base
          env
          which mamba
          which conda
          mkdir ${GITHUB_WORKSPACE}/envs ${GITHUB_WORKSPACE}/pytest
          bash ${GITHUB_WORKSPACE}/bin/gh-actions/setup-bactopia-env.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE} 0 "${GITHUB_WORKSPACE}/envs/bactopia-${GITHUB_ID}" "bactopia-${GITHUB_ID}"
          conda activate ${GITHUB_WORKSPACE}/envs/bactopia-${GITHUB_ID}
          export PATH=${GITHUB_WORKSPACE}/envs/bactopia-${GITHUB_JOB}/bin:${PATH}
          uname -a && env
          BACTOPIA_ARGS="--condadir ${CONDA_CACHE} --test_data_dir ${GITHUB_WORKSPACE}/bactopia-tests/data" TMPDIR=${GITHUB_WORKSPACE}/pytest pytest --symlink --kwdof --ignore conda/ --ignore modules/local/bactopia-tools/ --tag bactopia

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs-debian
          path: |
            ${GITHUB_WORKSPACE}/pytest/pytest_workflow_*/*/log.out
            ${GITHUB_WORKSPACE}/pytest/pytest_workflow_*/*/log.err
