name: test-bactopia-conda

on: workflow_dispatch
  #schedule:
    # At 01:30 on Monday and Thursday
    #- cron:  '30 1 * * 1,4'

jobs:
  bactopia-testing-conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2

      - name: Free up Disk Space
        run: bash ${GITHUB_WORKSPACE}/bin/gh-actions/free-disk-space.sh

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bactopia
          auto-activate-base: false

      - name: Setup Bactopia Environment
        run: bash ${GITHUB_WORKSPACE}/bin/gh-actions/setup-bactopia-env.sh ${CONDA} ${GITHUB_WORKSPACE} 1

      - name: Environment Information
        run: uname -a && env

      - name: Prepare for Bactopia Test
        run: mkdir -p ${GITHUB_WORKSPACE}/bactopia-testing/bactopia

      - name: Build Bactopia Datasets
        working-directory: ./bactopia-testing 
        run: | 
          bactopia datasets --species "Staphylococcus aureus" --limit 5  --ariba "card"
          git clone -b staphopia-v1 https://github.com/bactopia/bactopia-datasets.git
          cp -r bactopia-datasets/species-specific/ datasets/
          rm -rf bactopia-datasets/

      - name: Testing SRA Accession
        working-directory: ./bactopia-testing/bactopia
        run: |
          bactopia --accession SRX4563634 --coverage 10 -ansi-log false --registry github \
                   --datasets ${GITHUB_WORKSPACE}/bactopia-testing/datasets \
                   --species "Staphylococcus aureus" --genome_size median --skip_checkm
